### ISSUE TITLE
MSVC Support?

### ISSUE THREAD

**Issue by CodeApex** [PlatformLab/NanoLog#12]
Hello! Are you all going to end up supporting MSVC? I would absolutely love to use this library, but I have zero experience with gcc, and MSVC is what I always use!

**Comment by syang0** [comment]
Hi CodeApex, thanks for your interest in NanoLog, but we have no plans to support MSVC in the foreseeable future. Additionally, NanoLog was developed for a Linux environment, so it may not compile at all in a Windows environment.

However, if you'd like to try compiling the sources with MSVC yourself, you just need to build the C++17 version of the library by compiling [these SRC files](https://github.com/PlatformLab/NanoLog/blob/dfdd4639b5731d69207dfd72a020e39972a8c720/runtime/GNUmakefile#L2) into a static library. Then you can just link it with your application to use NanoLog.
