### ISSUE TITLE
possible to specify log filenames?

### ISSUE THREAD

**Issue by shi-yan** [PlatformLab/NanoLog#13]
also, is it possible to let each thread write to its own log file?
when a log file becomes huge, can I restart a new log file?

I want to adopt this for a server app, which will run for months. Having a huge log file with all threads' outputs mixed together isn't convenient for processing.

Thanks.

**Comment by syang0** [comment]
Hello, shi-yan.

It is currently not possible to output each thread’s log messages to a different log file. However, each log message is tagged with a NanoLog-assigned thread identifier that you might be able to use for your post-processing.

To switch log files, you can use the NanoLog::setLogFile(char*) API defined in [runtime/NanoLog.h](https://github.com/PlatformLab/NanoLog/blob/dfdd4639b5731d69207dfd72a020e39972a8c720/runtime/NanoLog.h#L83).

**Comment by shi-yan** [comment]
Thank you very much!

One more question, when logs from multiple threads are mixed in one file, threads won't interference with each other, right? For example, when using std::cout from multiple threads, I will see messed-up log outputs that are formed by logs from a few threads mixed together .

**Comment by syang0** [comment]
That is correct! When multiple threads log to the same file, there will only be a single log message per line.
