### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tiantianaixuexi** [PlatformLab/NanoLog#34]
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c Cycles.cc -o Cycles.o
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c Util.cc -o Util.o
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c testHelper/GeneratedCode.cc -o testHelper/GeneratedCode.o
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c Log.cc -o Log.o
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c NanoLog.cc -o NanoLog.o
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c RuntimeLogger.cc -o RuntimeLogger.o
g++ -std=c++17 -g -O3 -DPREPROCESSOR_NANOLOG -I. -ItestHelper -I"../googletest/googletest"/include -c TimeTrace.cc -o TimeTrace.o
g++ -std=c++11 -isystem "../googletest/googletest"/include -I"../googletest/googletest" -c "../googletest/googletest"/src/gtest-all.cc -L. -lgtest -lrt -pthread
g++: error: ../googletest/googletest/src/gtest-all.cc: No such file or directory
GNUmakefile:44: recipe for target 'libgtest.a' failed
make: *** [libgtest.a] Error 1

**Comment by syang0** [comment]
You need to initialize the gtest submodule in the main repository.

`git submodule update --init`

**Comment by syang0** [comment]
Hi tiantianaixuexi,

I've changed the GNUmakefile so it does not build the unit tests by default, and I've added a supplemental guide to building the unit tests in the README.md. Hopefully this'll prevent future confusion.

Best Regards,
Stephen Yang

**Comment by tiantianaixuexi** [comment]
OK，Thank you
