### ISSUE TITLE
cyclesDiskIO_upperBound

### ISSUE THREAD

**Issue by oPiZiL** [PlatformLab/NanoLog#40]
https://github.com/PlatformLab/NanoLog/blob/dc0efa1509c27eb2b786455547307c665ca2bf6a/runtime/RuntimeLogger.cc#L579  

maybe should be 
```
cyclesDiskIO_upperBound += (start - cyclesAtLastAIOStart); 
```

**Comment by syang0** [comment]
Good catch! I had moved around the start and cyclesAtLastAIOStart variables in my last commit ( 49771b54 ), and I didn't notice that the metrics were a little muddled. I'll patch it right now.
