### ISSUE TITLE
Outdated benchmarks

### ISSUE THREAD

**Issue by ArekPiekarz** [PlatformLab/NanoLog#6]
README contains comparisons with other logging libraries without stating their versions - except for Boost 1.55, which came out 5 years ago in 2013. I presume other libraries in your tests are also as outdated as Boost.Log.

Can you update the benchmarks to reflect the current performance of the logging systems?

**Comment by syang0** [comment]
Sorry for not including the information in the README.md (which has been updated in response to this issue), but I believe that Boost may be the only outdated system. Here's a summary of the software versions we benchmarked against.

- spdlog v1.1.0 (1/11/18) from commit 35865ee54e3c1d537827cb0f88858d10e174cca5
- Log4j2 v2.8 (1/27/2017)
- glog v0.3.5 (1/16/18) from commit 3106945d8d3322e5cbd5658d482c9ffed2d892c0
- ETW was benchmarked on Windows 10.0.16299.0

Given the relatively stable performance trend of traditional logging systems, it's unlikely that a newer version of Boost would see significantly better performance, so we'll leave that comparison at 1.55.
