### ISSUE TITLE
Allocation fails with printing concatenated string / integer data

### ISSUE THREAD

**Issue by runnerrunnerrunner** [PlatformLab/NanoLog#7]
For either the benchmarking code or the sample application, switching 
`
         "NANO_LOG(NOTICE, \"Starting backup replica garbage collector thread\");"
`
for
`       NANO_LOG(NOTICE, "A string, pointer, number, and float: '%s', %p, %d, %f",
                        randomString,
                        &randomString,
                        512,
                        3.14159);
`
in the logging loop causes RuntimeLogger::reserveAlloc() to fail. 
`
Platform: sles12sp1, Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz, 125GB of RAM.
`
NanoLog will write a random (usually between 50 and 200 MB) amount of data before the thread crashes and NanoLog is stuck waiting for more data to compress.

**Comment by syang0** [comment]
Based on the symptoms you described, it sounds like the variable `randomString` was not properly **null-terminated**.  I tested with `char randomString[] = "Hello World";` and the application seemed to work as normal.

If that doesn't fix your problem, maybe I misunderstood your setup. Below are the two test case I tried; let me know if I did something different from you.

-----
I changed [this line in the sample application](https://github.com/PlatformLab/NanoLog/blob/11a8cba58a4992632b03a3f11a67ecc4b445e1b3/sample/main.cc#L57) to be `"NANO_LOG(NOTICE, \"Starting backup replica garbage collector thread\");"`  and it seemed to work.

I also tried changing the the `#define BENCH_OPS` in the generated NanoLog/benchmarks/BenchmarkConfig.h file to be
`#define BENCH_OPS NANO_LOG(NOTICE, "A string, pointer, number, and float: '%s', %p, %d, %f", randomString, &randomString, 512, 3.14159);` **and** I added `char randomString[] = "Hello World";` to [NanoLog/benchmarks/Benchmark.cc:42](https://github.com/PlatformLab/NanoLog/blob/11a8cba58a4992632b03a3f11a67ecc4b445e1b3/benchmarks/Benchmark.cc#L42) and it seemed to work.
